version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb 
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:password@mongodb:27018/mjestic_cup_db?authSource=admin

  mongodb:
    image: mongo:latest
    container_name: majestic_cup_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
    command: [ "mongod", "--config", "/etc/mongod.conf" ]

volumes:
  mongodb_data:
